### PR TITLE
Added a parameter for force-updating cached json

### PR DESCRIPTION
**Pull request by bvanderdrift**

### CODE REVIEW

**Comment by skamoen** [comment]
Maybe add sponsors as well?

**Comment by martijn9612** [comment]
Everything still works, wouldn't have expected otherwise.

**Comment by skamoen** [comment]
Not sure how to test this, but at least the JSON's work fine here, so I assume browser-magic will fix the cache stuff

**Comment by martijn9612** [comment]
I believe this does not apply to the sponsors. They are on their own element, and do not use json.

**Comment by skamoen** [comment]
Good point, I see they use inline json which doesn't have the issue indeed.

**Pull request merged**
