### PR TITLE
Extract lancie-message-card to fix width of all message cards

### LINKED ISSUE #94: [Mobile] Profile intercept width
The width of the profile intercept is too wide on mobile

### LINKED ISSUE #95: [Mobile] Check your email element width
The width of the 'check your email' element is too wide on mobile.

### PR DESCRIPTION
**Pull request by TimvdLippe**
Fixes #94 
Fixes #95

### CODE REVIEW

**Comment by skamoen** [comment]
Better, but the intercept is not very usable now

image

The other cards are looking good

**Comment by TimvdLippe** [comment]
Any design on how we could improve this @martijn9612 ?

**Comment by skamoen** [comment]
Just making those inputs wrap would work just fine I think

**Comment by TimvdLippe** [comment]
Updated!

**Comment by skamoen** [comment]
LGTM

**Pull request merged**
