### PR TITLE
Updated HS tournament times to match the currently proposed planning

### PR DESCRIPTION
**Pull request by Exclaminator**

### CODE REVIEW

**Comment by martijn9612** [comment]
If you chane the starting times, please change the colspans accordingly.

**Comment by Exclaminator** [comment]
Jup, im on it

**Comment by Exclaminator** [comment]
Collspans are updated, please review again

Met vriendelijke groet,
Youri Arkesteijn

**Comment by martijn9612** [comment]
Please next time, just make a pr. I can't view the changes locally without cloning your repository. It looks ok tough.

**Pull request merged**
