### PR TITLE
Use font-awesome svg's instead of css

### LINKED ISSUE #30: Replace font-awesome icons with svgs
This would dismiss one more dependency. We don't need 600+ icons, just the 7 we need.

https://github.com/encharm/Font-Awesome-SVG-PNG/tree/master/black/svg

### PR DESCRIPTION
**Pull request by TimvdLippe**
Now we don't need to download the whole `font-awesome` package, just the icons we need. Saves some bandwidth again. Also speeds up the uploading process, as we do not need the `bower_components/` in `dist/` (already inserted into the main files)

Fixes #30

### CODE REVIEW

**Comment by TimvdLippe** [comment]
Run `gulp serve:dist` to test this branch btw. To make sure the new `dist/` is correctly working on your computer.

**Comment by TimvdLippe** [comment]
Rebased on current master.

**Comment by skamoen** [comment]
Yeeeeeaaaaaa no.

image

**Comment by skamoen** [comment]
How it's currently:

image

**Comment by TimvdLippe** [comment]
Updated the sizes. I did not change the sizes of the images before, however apparently the .css has different sizing than the .svg.

**Comment by skamoen** [comment]
Better now. LGTM.

**Pull request merged**
