### PR TITLE
Materialize orders

### LINKED ISSUE #61: Properly materialize My Area: Orders & Tickets
It's just functional for now, but it's not as pretty as intended or as the rest of the site. Fix this shit. Soon. ish.

### PR DESCRIPTION
**Pull request by martijn9612**
Fixes #61 
Still need some help with aligning the order information. Dialog needs alignment, too. For some reason I can't find out why the formatting isn't correctly applied. @TimvdLippe could you take a look at this issue?

### CODE REVIEW

**Comment by TimvdLippe** [comment]
I was able to fix the table header, but not the dialog. Can't seem to figure that one out sadly :sob:

**Comment by martijn9612** [comment]
I think that all the previous issues have been fixed by now. Could someone take a look at this? If all is well, we can marge this.

**Comment by skamoen** [comment]
The overall design is good, but the information isn't presented well enough. 

For example, an order row simply states "#175 2016-04-18 12:14 WAITING". This needs some more explanation like "Order: #175 Ordered on: 2016-04-18 12:14 Status: WAITING". Same for the dialog.

Futhermore, change the toggle of the dialog to a information icon at the end of the line, instead of the entire line.

**Comment by martijn9612** [comment]
The remarks you had should now be gone. Let me hear anything if something should be changed @skamoen.

**Comment by skamoen** [comment]
The Order dialog still opens on the entire list entry, instead of just the icon. Lastly, this part is still a bit random and could use some information on what it is.

image

**Comment by martijn9612** [comment]
I thought the click on the entire row would be okay, since the row and icon click both work. I will change it to the correct button though.

**Comment by martijn9612** [comment]
@skamoen Back to you. Information info and alignment is fixed now.

**Comment by skamoen** [comment]
LGTM. Merge TicketTransfer in this first.

**Comment by martijn9612** [comment]
LGTM

**Pull request merged**
