### PR TITLE
Swap the colours of the seats of yourself and your teammates.

### PR DESCRIPTION
**Pull request by MatthijsKok**

### CODE REVIEW

**Comment by FrancisBehnen** [comment]
Did you test this? Both myself and my teammates are yellow now for me.

**Comment by MatthijsKok** [comment]
No i did not. Thought it to be a simple fix

**Comment by martijnjanssen** [comment]
This also works perfectly in firefox and chrome. If it does not work, please specify.

**Comment by FrancisBehnen** [comment]
Restarted api, and now it's fine. Don't know what's going on here, but whatever..

**Pull request merged**
