### PR TITLE
Fix lancie timeline

### PR DESCRIPTION
**Pull request by FrancisBehnen**
Well, that was easier then expected :p

This does not fix the issue about the timeline since that was about rewriting the thing.

I want this pr to be about the technical side of the timeline. We'll create a separate PR to update the actual content.

### CODE REVIEW

**Comment by MatthijsKok** [comment]
- [ ] Update the content of the timeline.
- [ ] Rebase off master instead of seatmap-speedup.

**Comment by FrancisBehnen** [comment]
Content update in #417

**Comment by martijnjanssen** [comment]
This does not work a 100% yet. The thing that is missing is the initially selected tab!

**Comment by FrancisBehnen** [comment]
That is a bug that's been in the toolbar already for months. Lets fix it in a separate PR.

**Comment by martijnjanssen** [comment]
LGTM.

**Pull request merged**
