### PR TITLE
Change banner text and links

### PR DESCRIPTION
**Pull request by elarb**
Changes the banner text and removes the links in the banner:

banner

### CODE REVIEW

**Comment by skamoen** [comment]
Photo's are already available, so let's link to the album at https://flitcie.ch.tudelft.nl/Bestuur-61/Area-FiftyLAN

**Comment by elarb** [comment]
Anything else we want to link to?

**Comment by skamoen** [comment]
The facebook page for updates next year? Something like "Stay updated" linking to https://www.facebook.com/areafiftylan/

**Comment by martijnjanssen** [comment]
Yeah, I think those contents will be the best choices for the tabs.

**Pull request merged**
