### PR TITLE
Add open graph capabilities

### LINKED ISSUE #284: Index.html misses metadata for social media and link sharing
Sharing https://areafiftylan.nl/ on Twitter/Facebook/Slack does not show a nice message. A meta link with `name="description"` and [Open Graph data](http://ogp.me/) should be added to show a nicer message.

### PR DESCRIPTION
**Pull request by martijnjanssen**
Fixes #284

### CODE REVIEW

**Comment by martijnjanssen** [comment]
Are there any suggestions for a better text in the description? 

@MatthijsKok @FrancisBehnen @thelottebryan

**Comment by TimvdLippe** [comment]
Hm, can we put this somewhere on a server to test this?

**Comment by martijnjanssen** [comment]
I checked using this tool: https://developers.facebook.com/tools/debug/og/object/

I'm fairly sure that this will do the job perfectly.

**Comment by TimvdLippe** [comment]
Did you publish this on a public server?

**Comment by TimvdLippe** [comment]
https://developers.facebook.com/tools/debug/og/object/?q=areafiftylan.nl works :smile:

**Comment by Fr4nc3sc0NL** [comment]
How can that work already if this isn't merged yet @TimvdLippe? Anyway, this is my suggestion for the description:

>Area FiftyLAN is the hottest gaming event of Delft. For the third year in a row over 200 gamers will gather and play their favourite on- and off-line games together for three days (and nights)!

**Comment by TimvdLippe** [comment]
@Fr4nc3sc0NL You can deploy this branch on a public server :wink: 

Actually, you can test this right now with the above url, since @martijnjanssen manually entered the og values on the server, but not the full branch.

**Comment by martijnjanssen** [comment]
Is this good to go @AreaFiftyLAN/lancie-17 ? If this is the case, please merge this.

**Comment by MatthijsKok** [comment]
LGTM

**Pull request merged**
