### PR TITLE
Add back updated timeline

### PR DESCRIPTION
**Pull request by Fastjur**
Signed-off-by: Jurriaan Den Toonder <jur.den.toonder@gmail.com>

### CODE REVIEW

**Comment by Fastjur** [comment]
whatsapp image 2018-02-15 at 00 46 20
whatsapp image 2018-02-15 at 00 46 40
whatsapp image 2018-02-15 at 00 46 56

**Comment by skamoen** [comment]
Is it intentional both CS:GO and Overwatch have an explicit final, here HS and LoL just have "tournament" on sunday?

**Comment by Fastjur** [comment]
It was not intentional. I renamed them all to `Finals`. I think that sounds best.

**Comment by Fastjur** [comment]
image
Updated sunday tab

**Pull request merged**
