### PR TITLE
Simplify seatcard methods & remove unneeded ajax call

### PR DESCRIPTION
**Pull request by martijnjanssen**

### CODE REVIEW

**Comment by FrancisBehnen** [comment]
Reload button is broken, error in the console if you click it.

**Comment by martijnjanssen** [comment]
Good catch, I'll fix it.

**Comment by FrancisBehnen** [comment]
Travis build is failing due to AWS problems, build does actually work.

https://lh6.googleusercontent.com/OMISfAWc9iC3w7UfE_UaTLsUHukrsNj6TgFsRqwMah3tRZjxxFoSm6j8PGzjnNk1aeM9bka1sbxG2po=w3098-h1924

**Comment by FrancisBehnen** [comment]
We'll merge as soon as travis is up (and successfully building) again

**Comment by martijnjanssen** [comment]
@FrancisBehnen

**Pull request merged**
