### PR TITLE
Enable shadow dom and fix incompatibility with previous implementation

### LINKED ISSUE #128: Consider enabling shadow-dom
Shadow dom is an performance increase for the browser that support it. The old browser will continue using all polyfills.

We need to investigate what CSS and JS is breaking. This is most likely only an issue in `index.html` with its files `app.js` and `main.css`.

### PR DESCRIPTION
**Pull request by TimvdLippe**
This version should now be compatible with both shady and shadow dom.
Most prominently lancie-activity-dialog had to be rewritten as it
was relying on illegal ::shadow selectors and styling

Fixes #128

### CODE REVIEW

**Comment by martijnjanssen** [comment]
It seems like the dom-if contents in the login-catch are rendered since the requests are showing up in my console. This should not happen as far as I know.

**Comment by martijnjanssen** [comment]
It also looks like something in the my-area styling changed. The title of the tickets card looks like it is missing some styling. 
image

**Comment by martijnjanssen** [comment]
While in the seatmap, just opening and closing seats for some time seems to slow down my browser incrementally. In the task manager you see the usage going to 100% for some reason.

**Comment by TimvdLippe** [comment]
The timing issue has been fixed, but it required using `iron-lazy-pages#2.0-preview`. The styling issue still has to be fixed, but not sure what we want to fix there.

**Comment by TimvdLippe** [comment]
Will wait till #323 is merged and then I will rebase this PR

**Comment by TimvdLippe** [comment]
> Why do some elements in lancie-content have a template and some do not?

Those inside a `login-check` are in a template, such that the template is stamped when the route is shown. This prevents the incorrect invocation of `attached`

**Comment by martijnjanssen** [comment]
The styling issue is now fixed, but the data binding is broken in my-area and some other pages.

**Comment by TimvdLippe** [comment]
> the data binding is broken in my-area and some other pages

Could you please be more specific? Have some time to debug now :tada:

**Comment by martijnjanssen** [comment]
Okay, I have checked yesterday and added some observers on for instance the `{{user}}` binding from content into `my-area`. The observer in `lancie-content` does get the user, but this value is not reflected in the user variable in `my-area`.

**Comment by MatthijsKok** [comment]
Since #323 is now merged, this is no longer blocked.

**Comment by TimvdLippe** [comment]
Rebased on top of current master. This PR can be once again reviewed and merged :smile:

**Comment by martijnjanssen** [comment]
Nice, great stuff!

**Pull request merged**
