### PR TITLE
Place order check behind login-check

### PR DESCRIPTION
**Pull request by martijnjanssen**
Please test this on the master branch and this branch to verify that this actually fixes the problem of having troubles verifying the order after purchase.

### CODE REVIEW

**Comment by skamoen** [comment]
After first logging in, the error still shows. Only after a refresh after login is the request fired with the correct auth token.

**Comment by skamoen** [comment]
Steps to reproduce:
1. Order ticket
2. At mollie screen, ctrl + click the "Return to webshop" button so it opens in new tab.
3. Log in
4. Error!
5. Refresh
6. Success!

**Comment by FrancisBehnen** [comment]
#### Safari
- [x]  Pay -> Congratulations page
- [x]  Cancel -> Cancelled page
- [x]  Failed -> Cancelled page
- [x]  No endstatus -> Unable to check page

**Comment by FrancisBehnen** [comment]
#### Chrome
- [x]  Pay -> Congratulations page
- [x]  Cancel -> Cancelled page
- [x]  Failed -> Cancelled page
- [x]  No endstatus -> Unable to check page

**Pull request merged**
