### PR TITLE
Allow saving profile edit with enter

### LINKED ISSUE #372: Profile edit form submit on enter doesn't change to non-edit view
When I submit the profile edit form in My Area, the regular edit buttons are still there and the form is still displayed. 

Submit on enter should trigger the same things as clicking the checkmark button

### PR DESCRIPTION
**Pull request by MatthijsKok**
Fixes #372

### CODE REVIEW

**Comment by FrancisBehnen** [comment]
Don't merge yet, I have the feeling something is wrong here. Let me investigate tonight/tomorrow

**Comment by FrancisBehnen** [comment]
As I expected, this makes it impossible to change gender without using a mouse to click. I liked that it was possible to change everything in your profile without needing your mouse. I think we should keep that feature.

**Comment by MatthijsKok** [comment]
What are you talking about? I can easily traverse the entire form with enter and tab.

**Comment by martijnjanssen** [comment]
It works in both chrome and firefox. If something does not work, please state: WHERE, WHEN, HOW. If you don't do this, we can't fix it.

**Comment by FrancisBehnen** [comment]
Ah, nvm. I used enter to bring up the gender dropdown, but you can do that with up/down arrow. Then it's fine.

**Comment by martijnjanssen** [comment]
LGTM.

**Pull request merged**
