### PR TITLE
Add nutanix logo

### PR DESCRIPTION
**Pull request by FrancisBehnen**

### CODE REVIEW

**Comment by skamoen** [comment]
Did you test?

The filename has a capital N, where the src doesn't

**Comment by skamoen** [comment]
I don't like the wrapping. I'm pretty sure the images can fit next to each other perfectly fine

**Comment by martijnjanssen** [comment]
Maybe we should disable the max-width in the lancie-section of the sponsors.

**Comment by martijnjanssen** [comment]
I created a separate issue for the wrapping.

**Comment by martijnjanssen** [comment]
LGTM.

**Pull request merged**
